"""
Various ID retrieval method types.
"""

# Key generation via database-specific ID method
# (i.e. auto-increment for MySQL, sequence for Oracle, etc.).

NATIVE = "native"

# Key generation via auto-increment.

AUTO_INCREMENT = "autoincrement"
 
# Key generation via sequences.

SEQUENCE = "sequence"

# Key generation via the IDBroker table.

ID_BROKER = "idbroker"
 
# No RDBMS key generation (keys may be generated by the
# application).

NO_ID_METHOD = "none"


VALID_ID_METHODS = [ NATIVE, AUTO_INCREMENT, SEQUENCE, ID_BROKER, NO_ID_METHOD ]

ID_GENERATOR_METHODS = [ NATIVE, AUTO_INCREMENT, SEQUENCE ]
